version: '3.8'

services:
  dotnet:
    image: ${COMPOSE_PROJECT_NAME}/dotnet
    user: root
    build:
      context: ./dotnet/
      args:
        - VERSION=${DOTNET_VERSION}
        - HTTPS_PORT=${DOTNET_HTTPS_PORT}
    ports:
      - '8000:${DOTNET_HTTPS_PORT}'
    volumes:
      - ../:/app:${MOUNT_FLAG}
    networks:
      - app
    
  sqldata:
    image: mcr.microsoft.com/mssql/server:${MSSQL_VERSION}
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - sql_data:/mssql

volumes:
  sql_data:
    driver: local
    
networks:
  app:
